// Code generated by MockGen. DO NOT EDIT.
// Source: invitation_repository.go
//
// Generated by this command:
//
//	mockgen -source=invitation_repository.go -destination=../../mocks/invitation_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/FrostBitzX/smart-task-ai/internal/domain/projects/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInvitationRepository is a mock of InvitationRepository interface.
type MockInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationRepositoryMockRecorder
	isgomock struct{}
}

// MockInvitationRepositoryMockRecorder is the mock recorder for MockInvitationRepository.
type MockInvitationRepositoryMockRecorder struct {
	mock *MockInvitationRepository
}

// NewMockInvitationRepository creates a new mock instance.
func NewMockInvitationRepository(ctrl *gomock.Controller) *MockInvitationRepository {
	mock := &MockInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationRepository) EXPECT() *MockInvitationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvitationRepository) Create(ctx context.Context, invitation *entity.ProjectInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvitationRepositoryMockRecorder) Create(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvitationRepository)(nil).Create), ctx, invitation)
}

// Delete mocks base method.
func (m *MockInvitationRepository) Delete(ctx context.Context, projectID, inviteeAccountID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, projectID, inviteeAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvitationRepositoryMockRecorder) Delete(ctx, projectID, inviteeAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvitationRepository)(nil).Delete), ctx, projectID, inviteeAccountID)
}

// ExistsPendingInvitation mocks base method.
func (m *MockInvitationRepository) ExistsPendingInvitation(ctx context.Context, projectID, inviteeAccountID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsPendingInvitation", ctx, projectID, inviteeAccountID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsPendingInvitation indicates an expected call of ExistsPendingInvitation.
func (mr *MockInvitationRepositoryMockRecorder) ExistsPendingInvitation(ctx, projectID, inviteeAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsPendingInvitation", reflect.TypeOf((*MockInvitationRepository)(nil).ExistsPendingInvitation), ctx, projectID, inviteeAccountID)
}

// FindByProjectAndInvitee mocks base method.
func (m *MockInvitationRepository) FindByProjectAndInvitee(ctx context.Context, projectID, inviteeAccountID uuid.UUID) (*entity.ProjectInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectAndInvitee", ctx, projectID, inviteeAccountID)
	ret0, _ := ret[0].(*entity.ProjectInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectAndInvitee indicates an expected call of FindByProjectAndInvitee.
func (mr *MockInvitationRepositoryMockRecorder) FindByProjectAndInvitee(ctx, projectID, inviteeAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectAndInvitee", reflect.TypeOf((*MockInvitationRepository)(nil).FindByProjectAndInvitee), ctx, projectID, inviteeAccountID)
}

// ListByInvitee mocks base method.
func (m *MockInvitationRepository) ListByInvitee(ctx context.Context, inviteeAccountID uuid.UUID, status string) ([]*entity.ProjectInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByInvitee", ctx, inviteeAccountID, status)
	ret0, _ := ret[0].([]*entity.ProjectInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByInvitee indicates an expected call of ListByInvitee.
func (mr *MockInvitationRepositoryMockRecorder) ListByInvitee(ctx, inviteeAccountID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByInvitee", reflect.TypeOf((*MockInvitationRepository)(nil).ListByInvitee), ctx, inviteeAccountID, status)
}

// ListByProject mocks base method.
func (m *MockInvitationRepository) ListByProject(ctx context.Context, projectID uuid.UUID, status string) ([]*entity.ProjectInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID, status)
	ret0, _ := ret[0].([]*entity.ProjectInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockInvitationRepositoryMockRecorder) ListByProject(ctx, projectID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockInvitationRepository)(nil).ListByProject), ctx, projectID, status)
}

// UpdateStatus mocks base method.
func (m *MockInvitationRepository) UpdateStatus(ctx context.Context, invitation *entity.ProjectInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockInvitationRepositoryMockRecorder) UpdateStatus(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockInvitationRepository)(nil).UpdateStatus), ctx, invitation)
}
