// Code generated by MockGen. DO NOT EDIT.
// Source: member_repository.go
//
// Generated by this command:
//
//	mockgen -source=member_repository.go -destination=../../mocks/member_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/FrostBitzX/smart-task-ai/internal/domain/projects/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectMemberRepository is a mock of ProjectMemberRepository interface.
type MockProjectMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectMemberRepositoryMockRecorder is the mock recorder for MockProjectMemberRepository.
type MockProjectMemberRepositoryMockRecorder struct {
	mock *MockProjectMemberRepository
}

// NewMockProjectMemberRepository creates a new mock instance.
func NewMockProjectMemberRepository(ctrl *gomock.Controller) *MockProjectMemberRepository {
	mock := &MockProjectMemberRepository{ctrl: ctrl}
	mock.recorder = &MockProjectMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMemberRepository) EXPECT() *MockProjectMemberRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectMemberRepository) Create(ctx context.Context, member *entity.ProjectMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectMemberRepositoryMockRecorder) Create(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectMemberRepository)(nil).Create), ctx, member)
}

// IsMember mocks base method.
func (m *MockProjectMemberRepository) IsMember(ctx context.Context, projectID, accountID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, projectID, accountID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockProjectMemberRepositoryMockRecorder) IsMember(ctx, projectID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockProjectMemberRepository)(nil).IsMember), ctx, projectID, accountID)
}
