// Package account provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package account

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateAccountJSONBody defines parameters for CreateAccount.
type CreateAccountJSONBody struct {
	ConfirmPassword string              `json:"confirm_password"`
	Email           openapi_types.Email `json:"email"`
	Password        string              `json:"password"`
	Username        string              `json:"username"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody CreateAccountJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new account
	// (POST /accounts)
	CreateAccount(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(c *fiber.Ctx) error {

	return siw.Handler.CreateAccount(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/accounts", wrapper.CreateAccount)

}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(ctx *fiber.Ctx) error
}

type CreateAccount201JSONResponse struct {
	// Data Response data
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateAccount400JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateAccount409JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type CreateAccount500JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount500JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(ctx *fiber.Ctx) error {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx.UserContext(), request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xWTW/bMAz9K4K2o5O4X4f6lnYZEKBoOqfbpQgMVaYTdZbkSXLboPB/HyTLzpdTNMXW",
	"Q28JRT6Rj3yUXzCVvJAChNE4esEKdCGFBvdHL4iCNGltyT1Jewr+lKCNPadSGBDuJymKnFFimBSDBy2F",
	"C6cL4MT+KpQsQBlWw6bEOKtZFoAjLO8fgBpcBRiUksqewDPhRQ71HSng6DQMA8xBazK3IRfDb0k8+vFz",
	"NL21cTtArecaFJ4UoFyCKCMshxS3gdooJuY2UJeUgtYbgRnJNbS+91LmQASuqgBbKpiCFEd3beTq8qAu",
	"tClrtpOnhUhBU8UKm5ati6Qo9vzabLb5p1JkOaMfTv75OvmXk+vvV+PLz8X8ZcNsF+1MGFCC5D0N6hFU",
	"r6Xq43pwtimA8fXtKL4eXiXTUfxrFCejOJ7En6ohY885mjrO0chFWr+a1WZbyVJR0AmhVJbCJP4woQqI",
	"gZ43ry+tzVZYRTHFk4Jo/SRVam2ciSsQc7PA0WkHMcAJy61fJhUnBkfe0uF6AGqpbbncNYqT58b12LZ9",
	"FXmyE7nFfQsTtFm1SQS71c46JuYAUmuB7LK6Xswb8+3KxAuxuX5tIrv1tDlBsU8P+dnbr7ZDRWOfzBwM",
	"pMinlJV5vnyriIwq/5uGmMjkLhPDmzHKpEKcCDJnYo7sHmMULLxhxlU35UQZdEv0bzQco+HNGAf4EZSu",
	"EY76YT+0BckCBCkYjvBJP+yfuPEyC1fgwM9F3SBZq21ry7oBQgQJeELeHTvQmtlx2joN21Ov3QuZLg/a",
	"uV8VZDjCXwarL5yBH6XBwYuj2myQ7WEtldXX0nF4dFB+JM8nGY7u9k3zP8rfa7TqeBxev2OP+qpZx7b2",
	"3UL17Vu6qAJ8Gob7Smo5HLz6uelAzt8BQtde9rN3pdH9/LunqOScqOX+yTZkrq2cG0vNnbduq6NdMBop",
	"yB2PRjZgtXiBg8Otl2sLW82qvwEAAP//lG0o/skLAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
