// Package account provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package account

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	// Limit Number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAccountJSONBody defines parameters for CreateAccount.
type CreateAccountJSONBody struct {
	ConfirmPassword string              `json:"confirm_password"`
	Email           openapi_types.Email `json:"email"`
	Password        string              `json:"password"`
	Username        string              `json:"username"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody CreateAccountJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all accounts
	// (GET /accounts)
	ListAccounts(c *fiber.Ctx, params ListAccountsParams) error
	// Create a new account
	// (POST /accounts)
	CreateAccount(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.ListAccounts(c, params)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(c *fiber.Ctx) error {

	return siw.Handler.CreateAccount(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/accounts", wrapper.ListAccounts)

	router.Post(options.BaseURL+"/accounts", wrapper.CreateAccount)

}

type ListAccountsRequestObject struct {
	Params ListAccountsParams
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(ctx *fiber.Ctx) error
}

type ListAccounts200JSONResponse struct {
	// Data Response data
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListAccounts500JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response ListAccounts500JSONResponse) VisitListAccountsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(ctx *fiber.Ctx) error
}

type CreateAccount201JSONResponse struct {
	// Data Response data
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateAccount400JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateAccount409JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type CreateAccount500JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount500JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all accounts
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// Create a new account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(ctx *fiber.Ctx, params ListAccountsParams) error {
	var request ListAccountsRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx.UserContext(), request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(ctx *fiber.Ctx) error {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx.UserContext(), request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYXU/jOBT9K5Z3HwPtAPNA3wp0VtUyhSnMsNKoqi7JTWOI7WA7lAr1v6/sfDRtXKDs",
	"LlrNWxPnnut7fO6H+0xDyTMpUBhNe89Uoc6k0OgedAIKo2n9bnoL0Z7Chxy1seuhFAaF+wlZlrIQDJOi",
	"c6elcOZhghzsr0zJDJVhBWwExr01iwxpj8rbOwwNXQYUlZLKruAT8CzFwkeEtHfU7QaUo9YwsyYn/bPp",
	"ePDt++Dq2tq1gOovG1D0IkPlNkhiYClGtDbURjExs4Y6D0PUes0whlRj/e2tlCmCoMtlQC0VTGFEez9r",
	"y5XzoAi0CmvS2qeFiFCHimV2WzYuiMi45NfuZpP/UIo4ZeGHk3/cJP/0YvTlfHj6azF/WjHro50Jg0pA",
	"uqdRPaLaq6n6uDP4vJ4Aw9H1YDzqn0+vBuMfg/F0MB5fjH+pAxmWnJMrxzkZOEv7XcFqVa1krkLUUwhD",
	"mQszLRer5zb3oUIwGE3Bra37vE6QGMZRG+AZmScoiEmQlFhkDpqU5jSgsVTcgtjQcM+a+VhEDiz1e3JL",
	"BKJIodZExk1fTfwCwoPNIj9wLthDjoRFKAyLGao2+EoKEIbTb/pm9OPr5Yn56+7snI3i7Cvc3My9ojBg",
	"cu13W6x5fImcW1lAaNijJYmJ8ufE4yHX9tg5bgmtXG172QDakCSzJ1ZDBzWnZTxBUxYTTxZtF1phuFe+",
	"bnbHDd1JETPFpxloPZfKHR1n4hzFzCS0d/SSdl6Xwg6oTYI5PFWfHtj6srI8fI1RD5n1JoJ2tP+Q1KIS",
	"t1mtDLelwvCsUkp5wFtz4M/51UKfZU/hyffjL6Pkj3txEJ3GrwqrsYHdQkyZNlWA+oUImUHuSbhzpo0N",
	"rUKwaVV9+bvCmPbob53VaNcp3XZer5irJgJKwaJQ14wJKDy/DF+2zgqzYdjKSLfbNWwfgdsBW0wloKdc",
	"Kk/luEnQJKisDhQSUEjsdySDGWoCj8BSuE2xKQmjck+fC2jKOPM0jlHOb4sy68IiGSqH3oT81K0B7Twx",
	"Q2UBZRxrfAOikUTfs4zE0iFXJDTwvfBGGvC1H/uaiA0frGh3Ya4UCuMJwONi41QLfxVPdXjB6nDecMiN",
	"ycM/N60HMy5zh5QzxvapatfhyAo8RVs1yi3FeZou3jos+TX078xKTMSyzUT/cugEwkFYicyInVdZiBbe",
	"MOOiu+KgDLkGfU/6Q9K/HNKAPqLSBcKn/e5+1+kyQwEZoz16uN/dP3SJahIXYKeuOb1nOvOJd4xGMXxE",
	"AiSt6lSa1rWKzJlJ1lUsK86HUVnc+qvCloECjgaVpr2fO6Qes+sPOSp7ZEXLq4W5Gs05PDFuJxSnb85E",
	"+eTT+ruz1LeVOjcae6m8+zJtEqzfzg+63Z3uIJCmF7Fj0J9V72sbW/rY0nMX2al1VImxnHguB5U4iCqV",
	"tpGhy4B+LtjxeaxZ7LzxpuduHTnnoBZV623q2WYXzHRjHKAT2zWl9uTGqZtDCBCB88Ywsp4AxUf9erWc",
	"Kk9ktNjpyN93pFtG2uV67bLlbdmS5Kf/gSS3TY8fosl60NwU5NG7BNn8x82BHL8DJGz8ufHf5cUWZbdT",
	"w51D8XYzO+rea1M7dTwaWV/AXV9Djg63rKL12DpZ/h0AAP//g/iY4swUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
