// Package account provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package account

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateAccountJSONBody defines parameters for CreateAccount.
type CreateAccountJSONBody struct {
	ConfirmPassword string              `json:"confirm_password"`
	Email           openapi_types.Email `json:"email"`
	Password        string              `json:"password"`
	Username        string              `json:"username"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody CreateAccountJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new account
	// (POST /accounts)
	CreateAccount(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(c *fiber.Ctx) error {

	return siw.Handler.CreateAccount(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/accounts", wrapper.CreateAccount)

}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(ctx *fiber.Ctx) error
}

type CreateAccount201JSONResponse struct {
	// Data Response data
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateAccount400JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateAccount409JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type CreateAccount500JSONResponse struct {
	Data    map[string]interface{} `json:"data"`
	Error   map[string]interface{} `json:"error"`
	Message string                 `json:"message"`
	Success bool                   `json:"success"`
}

func (response CreateAccount500JSONResponse) VisitCreateAccountResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(ctx *fiber.Ctx) error {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx.UserContext(), request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xWwY7bNhD9FYLtUbaV3c1hdfN6nULowk5lp5fAELjUyGYikSpJZdcI9O8FKYqWbTmt",
	"gzaH3GyS8zTvzbwhv2Iqykpw4Frh6CuWoCrBFdg/akckZKlfS59JNpLwVw1Km30quAZuf5KqKhglmgk+",
	"+aQEt+F0ByUxvyopKpCatbAZ0XZV7yvAERbPn4Bq3AQYpBTS7MArKasC2m9kgKO7MAxwCUqRrQl5mD6m",
	"yfyPD/PV2sSdAfmTPSi8rEDaBFFOWAEZ9oFKS8a3JlDVlIJSR4E5KRT4s89CFEA4bpoAGymYhAxHH33k",
	"4eNBS7SjtTnL00BkoKhklUnL8CIZSpy+JptT/angecHoDxf/vi/+bLl49xTPfi7lZ52yQ7IzrkFyUowU",
	"yC8gR16qH1eDt8cGiBfrebKYPqWrefLnPEnnSbJMfqqCxE5ztLKao7mNNOdaVbtpJWpJQaWEUlFznbrN",
	"lEogGkZuuT+0jkthHMVkmVZEqRchM7NWMv4EfKt3OLobEAZKwgpzLheyJBpHbmXg6BWotTJ0S1uokrx2",
	"R29M2Q+Rt2eRJ9p7mMBn5ZMIztluBjrmClFbg5yr2gUyy/y4sOsdoPgRiRzpHaAWMkMuwqTtu5RQmv7+",
	"stqrx+qVPny4f7fY/faZ32SzHP+TDL0Ehig6h3e8eq0+bNRjBonjjVxTX7bxtW40d3EBRg+XUl4Xxf7f",
	"ulPL+n8zJ+O5OFdi+j5GuZCoJJxsGd8iMyAZBQOvmbbsViWRGq2J+oymMZq+j3GAv4BULcKbcTgODSFR",
	"AScVwxG+HYfjW9u3emcJTlw12wKJ1sYn49u2ESKIw0uvl0SnbJz5Q1O/64bCg8j2Vw3zXyXkOMK/TA5P",
	"p4lrpcnVE6k5LpCpYevBwzPsJnxzVX6kKJY5jj5e6ub/KH9n/mbg1vn2Ny64r9kMXAOuWn5OHPmiCfBd",
	"GF6i5DWcfPMda0HuvwOE9p4Mb78rjeF3hb3j6rIkcn+5szXZqt6gw612bvXUHX7AKCShsDpq0YG15oUS",
	"LG57BXnYZtP8HQAA//8soYpIIgwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
